name       : gstreamer-vaapi
version    : 1.18.5
release    : 15
source     :
    - https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/archive/1.18.5/gstreamer-vaapi-1.18.5.tar.gz : 2e6dae754f9c6e3367feeca82b0a764671febea1db3d05638b31c5eeaad4e264
license    : LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : VAAPI backend for GStreamer
description: |
    A collection of GStreamer plugins to let you make use of VA API video
    acceleration from GStreamer applications.

    Includes elements for video decoding, display, encoding and post-processing
    using VA API (subject to hardware limitations).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gstreamer-codecparsers-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libdrm)
    - pkgconfig(libudev)
    - pkgconfig(libva)
    - pkgconfig(vpx)
    - pkgconfig(wayland-client)
    - pkgconfig(xrandr)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
