name       : gstreamer-vaapi
version    : 1.20.3
release    : 16
source     :
    - https://gstreamer.freedesktop.org/src/gstreamer-vaapi/gstreamer-vaapi-1.20.3.tar.xz : 6ee99eb316abdde9ad37002915bd8c3867918f6fdc74b7cf2ac4c1ae0d690b45
license    : LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : VAAPI backend for GStreamer
description: |
    A collection of GStreamer plugins to let you make use of VA API video
    acceleration from GStreamer applications.

    Includes elements for video decoding, display, encoding and post-processing
    using VA API (subject to hardware limitations).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gstreamer-codecparsers-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libdrm)
    - pkgconfig(libudev)
    - pkgconfig(libva)
    - pkgconfig(vpx)
    - pkgconfig(wayland-client)
    - pkgconfig(xrandr)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
