name       : gstreamer-vaapi
version    : 1.14.2
release    : 7
source     :
    - https://gstreamer.freedesktop.org/src/gstreamer-vaapi/gstreamer-vaapi-1.14.2.tar.xz : 7f1064e27f5abd3a42ef66b425f1a2b9dbae7748c81bd9d090ce52a1aaf30d8a
license    : LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : VAAPI backend for GStreamer
description: |
    A collection of GStreamer plugins to let you make use of VA API video
    acceleration from GStreamer applications.

    Includes elements for video decoding, display, encoding and post-processing
    using VA API (subject to hardware limitations).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gstreamer-codecparsers-1.0)
    - pkgconfig(libdrm)
    - pkgconfig(libudev)
    - pkgconfig(libva)
    - pkgconfig(vpx)
    - pkgconfig(wayland-client)
    - pkgconfig(xrandr)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
