name       : gstreamer-vaapi
version    : 1.16.0
release    : 10
source     :
    - https://gstreamer.freedesktop.org/src/gstreamer-vaapi/gstreamer-vaapi-1.16.0.tar.xz : 4e7fce626ee0590dca74b5a8341d25bac76307945131a970b414fc5895f5171f
license    : LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : VAAPI backend for GStreamer
description: |
    A collection of GStreamer plugins to let you make use of VA API video
    acceleration from GStreamer applications.

    Includes elements for video decoding, display, encoding and post-processing
    using VA API (subject to hardware limitations).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gstreamer-codecparsers-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libdrm)
    - pkgconfig(libudev)
    - pkgconfig(libva)
    - pkgconfig(vpx)
    - pkgconfig(wayland-client)
    - pkgconfig(xrandr)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
