name       : gstreamer-vaapi
version    : 1.18.2
release    : 14
source     :
    - https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/archive/1.18.2/gstreamer-vaapi-1.18.2.tar.gz : ce658abf333f50dcf71afbeda1254149f6c7a992702b9ffbf58ec3ccf7fb2d99
license    : LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : VAAPI backend for GStreamer
description: |
    A collection of GStreamer plugins to let you make use of VA API video
    acceleration from GStreamer applications.

    Includes elements for video decoding, display, encoding and post-processing
    using VA API (subject to hardware limitations).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gstreamer-codecparsers-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libdrm)
    - pkgconfig(libudev)
    - pkgconfig(libva)
    - pkgconfig(vpx)
    - pkgconfig(wayland-client)
    - pkgconfig(xrandr)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
