name       : gstreamer-vaapi
version    : 1.12.3
release    : 4
source     :
    - https://gstreamer.freedesktop.org/src/gstreamer-vaapi/gstreamer-vaapi-1.12.3.tar.xz : f4cdafd8fd9606a490917c8b67336e835df1219580d55421c70480fd0913744d
license    : LGPL-2.1
component  : multimedia.gstreamer
summary    : VAAPI backend for GStreamer
description: |
    A collection of GStreamer plugins to let you make use of VA API video
    acceleration from GStreamer applications.
    
    Includes elements for video decoding, display, encoding and post-processing
    using VA API (subject to hardware limitations).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gstreamer-codecparsers-1.0)
    - pkgconfig(libdrm)
    - pkgconfig(libudev)
    - pkgconfig(libva)
    - pkgconfig(libva-drm)
    - pkgconfig(libva-wayland)
    - pkgconfig(vpx)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
