name       : gstreamer-vaapi
version    : 1.22.3
release    : 18
source     :
    - https://gstreamer.freedesktop.org/src/gstreamer-vaapi/gstreamer-vaapi-1.22.3.tar.xz : a27867062e8b69305fca5b7d3f13ed7c318b703e7d72756c94395bd305c7b32c
license    : LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : VAAPI backend for GStreamer
description: |
    A collection of GStreamer plugins to let you make use of VA API video
    acceleration from GStreamer applications.

    Includes elements for video decoding, display, encoding and post-processing
    using VA API (subject to hardware limitations).
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gstreamer-codecparsers-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libdrm)
    - pkgconfig(libudev)
    - pkgconfig(libva)
    - pkgconfig(vpx)
    - pkgconfig(wayland-client)
    - pkgconfig(xrandr)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
