name       : gstreamer-vaapi
version    : 0.7.0
release    : 2
source     :
    - https://freedesktop.org/software/vaapi/releases/gstreamer-vaapi/gstreamer-vaapi-0.7.0.tar.bz2 : abe8ea4dfb3177d038b38610537c651b943707ed110882782a19b95a9ea04a92
license    : MIT
summary    : VAAPI backend for GStreamer
description: |
    VAAPI backend for gstreamer
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libudev)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(gl)
    - pkgconfig(wayland-client)
    - pkgconfig(libva-drm)
    - pkgconfig(libva)
    - pkgconfig(libva-wayland)
    - pkgconfig(vpx)
    - pkgconfig(gstreamer-plugins-base-1.0)
setup      : |
    %configure --disable-static --disable-builtin-libvpx
build      : |
    %make
install    : |
    %make_install
