name       : gstreamer-vaapi
version    : 0.5.10
release    : 1
source     :
    - http://freedesktop.org/software/vaapi/releases/gstreamer-vaapi/gstreamer-vaapi-0.5.10.tar.bz2 : 0dd236c7bf225322b8934fdba99a7a9e4542566a2acbe7564cdc3ec2c8b73c9d
license    : MIT
summary    : VAAPI backend for GStreamer
description: |
    VAAPI backend for gstreamer
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libudev)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(gl)
    - pkgconfig(wayland-client)
    - pkgconfig(libva-drm)
    - pkgconfig(libva)
    - pkgconfig(libva-wayland)
    - pkgconfig(vpx)
    - pkgconfig(gstreamer-plugins-base-1.0)
setup      : |
    %configure --disable-static --disable-builtin-libvpx
build      : |
    %make
install    : |
    %make_install
